### ISSUE TITLE
thank you!

### ISSUE THREAD

**Issue by RYAN-dot-LOCAL** [utkusen/jeopardize#1]
This looks really cool.   Thanks for making this.

If you want to increase your alexa check to include 700 million harmonic page rank domains, here is the webpage and the direct link for it.   You obviously don't need to use all 700 million domains.  Note the data is in reverse order.  com.github, com.google, etc.

webpage
https://commoncrawl.org/connect/blog/

(16.32 GB	)
https://commoncrawl.s3.amazonaws.com/projects/hyperlinkgraph/cc-main-2019-20-nov-dec-jan/host/cc-main-2019-20-nov-dec-jan-host-ranks.txt.gz

**Comment by utkusen** [comment]
Thank you I will take a look
