### ISSUE TITLE
RuntimeError "An attempt has been made to start a new process before the current process has finished its bootstrapping phase." on Windows

### ISSUE THREAD

**Issue by FIying-Scotsman** [utkusen/jeopardize#2]
Currently when running the script on Windows 10 (1909 using Python 3.8.2), it will spam the console with errors (in between printing info).

The most common error message is:

```
File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
RuntimeError    : raise RuntimeError('''
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
There are other errors relating to multiprocessing\spawn.py but there's no consistent errors. Each run produces different line numbers and errors, but the same RuntimeError message appears.

I managed to narrow it down to:

https://github.com/utkusen/jeopardize/blob/15a23ee30494228a30409fa9882d0647f1dbd655/jeopardize.py#L486

As putting that line inside a `if __name__ == '__main__':` clause stops the errors but output isn't printed out as often as it was before as it would print lines like:

> Creating combinations: Creating combinations:  facebook.com

But that is no longer the case with that tweak (it just sits on "This will take a while.."). 

I ran the unmodified script in a Linux Mint VM (19.3 using Python 3.7.6) and don't get any errors, but output just stops at: 
> This will take a while..

So is that intentional (the capped output) or is it a side effect?

**Comment by utkusen** [comment]
Well, it's not tested on Windows but the `This will take a while..` is expected. In the brute mode, it actually takes a while. You can use `-v` (verbose) flag to observe progress.

**Comment by FIying-Scotsman** [comment]
Thanks for the reply. The tweak I tried (combined with the -v flag you suggested) looks like it's fixed the error spam as the script is working as intended (seems to work on both Linux and Windows).
