### ISSUE TITLE
Working on a similar project

### ISSUE THREAD

**Issue by freeload101** [utkusen/jeopardize#3]
https://github.com/freeload101/Python/blob/master/GonePhishin/GonePhishin.py

* ingest URLs clicked my mail gateway
* click all the things fill all the forms
* diff valid test credentials compared to fake ( if not different then phishing )
* determine based on keywords like o365 company name etc if the site is phishing
* inspect all documents 2-3 deep 
- unzip files
- inspect documents with 'binaries' pdf,office js,zip etc
- follow all links in documents (pdf word etc repeat from start )

**Comment by utkusen** [comment]
very cool. I will check it.
